### PR TITLE
Update change from AJO

### PR DESCRIPTION
**Pull request by jaapjansma**
Hans,

Could you merge this changes in your original extension? This way it works in CiviCRM 4.7

Jaap

### CODE REVIEW

**Comment by catorghans** [comment]
Does it then still work in 4.6?

**Comment by jaapjansma** [comment]
Ehm good question. Shall I rewrite it with a version check?

**Comment by catorghans** [comment]
yes, please. Or test first, it might just work. Even a change like this

**Comment by jaapjansma** [comment]
@catorghans I am more than willing to test but I don't have a civicrm 4.6 version and I don't have access to an omnikassa test account.

**Comment by catorghans** [comment]
ok, then version check makes sense

**Comment by jaapjansma** [comment]
Ok. See my other PR for a PR with a version check.

**Pull request closed without merging**
